jobs:
  build:
    runs-on: ubuntu-latest
    name: script/cibuild
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Set up Environment
        run: |
          bundle config path vendor/bundle
          export JEKYLL_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: script/bootstrap
      - name: Test
        run: script/cibuild
